#Build
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY chatbot /app/chatbot
RUN mvn package -f /app/chatbot/pom.xml

#multi-staging
FROM openjdk:17-slim  
WORKDIR /app
COPY --from=build /app/chatbot/target/chatbot-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
CMD ["java","-jar","app.jar"]
 #docker build -t chatbot:1.0.0 -f ./DockerFile .

